# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 3.5

before_install:
  - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends fsl-core fsl-atlases fsl-mni-structural-atlas fsl-mni152-templates fsl-first-data afni
  - PYTHONPATH=$PYTHONPATH:$(pwd)

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
  - pip uninstall --yes dipy
  - git clone https://github.com/nipy/dipy.git && cd dipy && python setup.py install && cd ..

env:
  global:
    - FSLDIR=/usr/share/fsl/5.0
    - AFNI=/usr/lib/afni/bin

# command to run tests, e.g. python setup.py test
script:
   - travis_wait 60 pytest tests/test_estimation.py -s
   - travis_wait 60 pytest tests/test_nodemaker.py -s
   - travis_wait 60 pytest tests/test_plotting.py -s
   - travis_wait 60 pytest tests/test_thresholding.py -s
   - travis_wait 60 pytest tests/test_utils.py -s
   - travis_wait 60 pytest tests/test_clustools.py -s
   - travis_wait 60 pytest tests/test_clustering.py -s
   - travis_wait 60 pytest tests/test_netstats.py -s
   - travis_wait 60 pytest tests/test_track.py -s
   - travis_wait 60 pytest tests/test_reg_utils.py -s
   - pytest tests/test_refs.py -s

after_success:
  - bash <(curl -s https://codecov.io/bash) -t d62ad7b3-39a6-4657-a2e3-6acf2362d36d
