# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.7
  - 3.6

before_install:
  - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
  - |
    wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.2.0/travis-wait-enhanced_1.2.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
    mv travis-wait-enhanced /home/travis/bin/
    travis-wait-enhanced --version
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends fsl-core fsl-atlases fsl-mni-structural-atlas fsl-mni152-templates
  - PYTHONPATH=$PYTHONPATH:$(pwd)
  - travis_retry wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 -c -O examples.tar.gz "https://osf.io/ye4vf/download" && tar -xvzf examples.tar.gz -C $TRAVIS_BUILD_DIR/tests

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
  - pip install git+https://github.com/dPys/nilearn.git
  - pip install codecov pytest-cov pytest-travis-fold
env:
  global:
    - FSLDIR=/usr/share/fsl/5.0

# command to run tests, e.g. python setup.py test
script:
   - travis-wait-enhanced --interval=1m --timeout=720m -- ./script_with_folds.sh

after_script:
  - codecov
