# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.7
  - 3.6

before_install:
  - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends fsl-core fsl-atlases fsl-mni-structural-atlas fsl-mni152-templates
  - PYTHONPATH=$PYTHONPATH:$(pwd)
  - wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q -O examples.tar.gz "https://osf.io/aq8ur/download"
  - tar -xvzf examples.tar.gz -C $TRAVIS_BUILD_DIR/tests

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
  - pip install git+https://github.com/dPys/nilearn.git
  - pip install codecov pytest-cov
env:
  global:
    - FSLDIR=/usr/share/fsl/5.0

# command to run tests, e.g. python setup.py test
script:
   - travis_wait 60 pytest tests/test_estimation.py -s
   - travis_wait 60 pytest tests/test_nodemaker.py -s
   - travis_wait 60 pytest tests/test_plotting.py -s
   - travis_wait 60 pytest tests/test_thresholding.py -s
   - travis_wait 60 pytest tests/test_utils.py -s
#   - travis_wait 120 pytest tests/test_clustering.py -s
   - travis_wait 60 pytest tests/test_netstats.py -s
   - travis_wait 60 pytest tests/test_track.py -s
   - travis_wait 60 pytest tests/test_reg_utils.py -s
   - travis_wait 60 pytest tests/test_dmri_utils.py -s
   - pytest tests/test_refs.py -s

after_script:
  - codecov
      token: d62ad7b3-39a6-4657-a2e3-6acf2362d36d
