# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
   - travis_wait 60 pytest tests/test_estimation.py -s
   - pytest tests/test_nodemaker.py -s
   - pytest tests/test_plotting.py -s
   - travis_wait 60 pytest tests/test_thresholding.py -s
   - travis_wait 60 pytest tests/test_utils.py -s
   - travis_wait 60 pytest tests/test_clustools.py -s
   - pytest tests/test_refs.py -s

after_success:
  - bash <(curl -s https://codecov.io/bash) -t d62ad7b3-39a6-4657-a2e3-6acf2362d36d
